const SET_USERS_DATA = 'SET_USERS_DATA',
SIGN_IN_TO_SITE = 'SIGN_IN_TO_SITE',
GET_USER_ROLE_INFO = "GET_USER_ROLE_INFO",
SET_USER_ROLE_INFO = "SET_USER_ROLE_INFO";

export { SET_USERS_DATA, SIGN_IN_TO_SITE, SET_USER_ROLE_INFO };